networks:
  toubilib.net:
    driver: bridge

services:
  # API GATEWAY
  api.gateway:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    ports:
      - '7080:80'
    volumes:
      - ./gateway:/var/php
    working_dir: /var/php
    networks:
      - toubilib.net
    depends_on:
      - api.toubilib
      - api.praticiens
      - api.rdv
      - api.auth

    command: sh -c "composer install && php -d opcache.enable=0 -S 0.0.0.0:80 -t /var/php/public"

  # SERVICE RDV
  api.rdv:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    ports:
      - '6082:80'
    volumes:
      - ./app-rdv:/var/php
    working_dir: /var/php
    networks:
      - toubilib.net
    depends_on:
      - toubirdv.db
    environment:
      - DB_HOST=toubirdv.db
    command: sh -c "composer install && php -d opcache.enable=0 -S 0.0.0.0:80 -t /var/php/public"

  # API AUTH
  api.auth:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    ports:
      - '6083:80'
    volumes:
      - ./app.auth:/var/php
    working_dir: /var/php
    networks:
      - toubilib.net
    depends_on:
      - toubiauth.db
    environment:
      - DB_HOST=toubiauth.db
    command: sh -c "composer install && php -d opcache.enable=0 -S 0.0.0.0:80 -t /var/php/public"

  # API TOUBILIB
  api.toubilib:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    ports:
      - '6080:80'
    volumes:
      - ./app:/var/php
    working_dir: /var/php
    networks:
      - toubilib.net
    depends_on:
      - toubipat.db
    environment:
      - DB_HOST=toubipat.db
    command: sh -c "composer install && php -d opcache.enable=0 -S 0.0.0.0:80 -t /var/php/public"


  # API PRATICIENS
  api.praticiens:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    ports:
      - '6081:80'
    volumes:
      - ./app-praticiens:/var/php
    working_dir: /var/php
    networks:
      - toubilib.net
    depends_on:
      - toubiprat.db

    command: sh -c "composer install && php -d opcache.enable=0 -S 0.0.0.0:80 -t /var/php/public"

  # BASES DE DONNÃ‰ES
  toubiprat.db:
    image: 'postgres:latest'
    env_file: ./toubipratdb.env
    ports: ['5432:5432']
    networks: [toubilib.net]
    volumes:
      - ./sql/toubiprat.schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./sql/toubiprat.data.sql:/docker-entrypoint-initdb.d/02-data.sql
    
  toubiauth.db:
    image: 'postgres:latest'
    env_file: ./toubiauthdb.env
    ports: ['5433:5432']
    networks: [toubilib.net]
    volumes:
      - ./sql/toubiauth.schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./sql/toubiauth.data.sql:/docker-entrypoint-initdb.d/02-data.sql

  toubirdv.db:
    image: 'postgres:latest'
    env_file: ./toubirdvdb.env
    ports: ['5434:5432']
    networks: [toubilib.net]
    volumes:
      - ./sql/toubirdv.schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./sql/toubirdv.data.sql:/docker-entrypoint-initdb.d/02-data.sql

  toubipat.db:
    image: 'postgres:latest'
    env_file: ./toubipatientdb.env
    ports: ['5435:5432']
    networks: [toubilib.net]
    volumes:
      - ./sql/toubipat.schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./sql/toubipat.data.sql:/docker-entrypoint-initdb.d/02-data.sql

  adminer:
    image: adminer
    ports: ['8080:8080']
    networks: [toubilib.net]

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'  
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - toubilib.net
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'
    networks:
      - toubilib.net

  app.mail:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    ports:
      - '6084:80'
    volumes:
      - ./app-mail:/var/php
    working_dir: /var/php
    networks:
      - toubilib.net
    depends_on:
      - rabbitmq
      - mailcatcher
    environment:
      - MAILER_HOST=mailcatcher
      - MAILER_PORT=1025
    command: sh -c "composer install && php -d opcache.enable=0 -S 0.0.0.0:80 -t /var/php/public"

volumes:
  rabbitmq_data: