networks:
  toubilib.net:
    driver: bridge

services:
  # API GATEWAY
  api.gateway:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    ports:
      - '7080:80'
    volumes:
      - ./gateway:/var/php
    working_dir: /var/php
    networks:
      - toubilib.net
    depends_on:
      - api.toubilib
      - api.praticiens
      - api.rdv

    command: sh -c "composer install && php -d opcache.enable=0 -S 0.0.0.0:80 -t /var/php/public"

  # SERVICE RDV
  api.rdv:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    ports:
      - '6082:80'
    volumes:
      - ./app-rdv:/var/php
    working_dir: /var/php
    networks:
      - toubilib.net
    depends_on:
      - toubirdv.db
    environment:
      - DB_HOST=toubirdv.db
    command: php -d opcache.enable=0 -S 0.0.0.0:80 -t /var/php/public

  # API TOUBILIB
  api.toubilib:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    ports:
      - '6080:80'
    volumes:
      - ./app:/var/php
    working_dir: /var/php
    networks:
      - toubilib.net
    depends_on:
      - toubiprat.db
      - toubirdv.db
    command: php -S 0.0.0.0:80 -t /var/php/public

  # API PRATICIENS
  api.praticiens:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    ports:
      - '6081:80'
    volumes:
      - ./app-praticiens:/var/php
    working_dir: /var/php
    networks:
      - toubilib.net
    depends_on:
      - toubiprat.db

    command: sh -c "composer install && php -S 0.0.0.0:80 -t /var/php/public"

  # BASES DE DONNÃ‰ES
  toubiprat.db:
    image: 'postgres:latest'
    env_file: ./toubipratdb.env
    ports: ['5432:5432']
    networks: [toubilib.net]
    volumes:
      - ./sql/toubiprat.schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./sql/toubiprat.data.sql:/docker-entrypoint-initdb.d/02-data.sql
    
  toubiauth.db:
    image: 'postgres:latest'
    env_file: ./toubiauthdb.env
    ports: ['5433:5432']
    networks: [toubilib.net]
    volumes:
      - ./sql/toubiauth.schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./sql/toubiauth.data.sql:/docker-entrypoint-initdb.d/02-data.sql

  toubirdv.db:
    image: 'postgres:latest'
    env_file: ./toubirdvdb.env
    ports: ['5434:5432']
    networks: [toubilib.net]
    volumes:
      - ./sql/toubirdv.schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./sql/toubirdv.data.sql:/docker-entrypoint-initdb.d/02-data.sql

  toubipat.db:
    image: 'postgres:latest'
    env_file: ./toubipatientdb.env
    ports: ['5435:5432']
    networks: [toubilib.net]
    volumes:
      - ./sql/toubipat.schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./sql/toubipat.data.sql:/docker-entrypoint-initdb.d/02-data.sql

  adminer:
    image: adminer
    ports: ['8080:8080']
    networks: [toubilib.net]